### ISSUE TITLE
Tests are exceeding block gas limit

### ISSUE THREAD

**Issue by Evert0x** [mudgen/diamond-3#16]
Hi, love the project :).

I'm using the latest version from Master. And the default tests are exceeding the block limit. 

`evert@EvertX1:~/piedao/Diamond$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
evert@EvertX1:~/piedao/Diamond$ truffle test
Using network 'development'.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

  Contract: Cache bug test
    ✓ should not exhibit the cache bug

  Contract: DiamondTest
    ✓ should have three facets -- call to facetAddresses function
    ✓ facets should have the right function selectors -- call to facetFunctionSelectors function (51ms)
    ✓ selectors should be associated to facets correctly -- multiple calls to facetAddress function (42ms)
    ✓ should get all the facets and function selectors of the diamond -- call to facets function
    ✓ should add test1 functions (139ms)
    ✓ should add test2 functions (171ms)
    ✓ should remove some test2 functions (90ms)
    1) should remove some test1 functions
    > No events were emitted
    2) remove all functions and facets accept diamondCut and facets
    > No events were emitted
    3) add most functions and facets
    > No events were emitted

  8 passing (3s)
  3 failing

  1) Contract: DiamondTest
       should remove some test1 functions:
     Error: Returned error: Exceeds block gas limit
      at Object.ErrorResponse (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-requestmanager/src/index.js:140:1
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  2) Contract: DiamondTest
       remove all functions and facets accept diamondCut and facets:
     Error: Returned error: Exceeds block gas limit
      at Object.ErrorResponse (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-requestmanager/src/index.js:140:1
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  3) Contract: DiamondTest
       add most functions and facets:
     Error: Returned error: Exceeds block gas limit
      at Object.ErrorResponse (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-requestmanager/src/index.js:140:1
      at /home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/home/evert/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

`

**Comment by mudgen** [comment]
I'm glad you love the project!

Okay.  My guess is that your development network is trying to execute all the tests within a single block. Because the `should remove some test1 functions` test isn't much gas and is less than some of the others that succeeded before it.

What software are you using for your development network?  I am using the graphical version of Ganache.

Is there some kind of setting in your development network to execute these tests in more than one block?   If no, are you able to increase the size of your block gas limit to 10 million or something?

**Comment by Evert0x** [comment]
I'm using ganace with `ganace-cli` It spawns a chain with `6721975`. But the tests are using `gas: 7000000`, which exceeds the max and marks them as failed immediately.

I created a fix in #17

**Comment by mudgen** [comment]
Oh I see.  Good catch.  Thanks very much for the pull request.  Merged.
